version: "3.5"

services:
  cassandra:
    container_name: sandbox-temporal-cassandra
    image: cassandra:3.11
    networks:
      - temporal-network
    ports:
      - 9042:9042

  temporal:
    container_name: sandbox-temporal
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:1.8.1
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: sandbox-temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.8.1
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  temporal-web:
    container_name: sandbox-temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.8.1
    networks:
      - temporal-network
    ports:
      - 8088:8088

  api:
    container_name: sandbox-temporal-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    depends_on:
      - worker-a
#      - worker-b
    networks:
      - temporal-network
    ports:
      - 8080:8080
    environment:
      - TEMPORAL_URL=temporal:7233

  worker-a:
    container_name: sandbox-temporal-worker-a
    build:
      context: .
      dockerfile: cmd/worker-a/Dockerfile
    depends_on:
      - temporal
      - temporal-web
    networks:
      - temporal-network
    environment:
      - TEMPORAL_URL=temporal:7233

  worker-b:
    container_name: sandbox-temporal-worker-b
    build:
      context: .
      dockerfile: cmd/worker-b/Dockerfile
    depends_on:
      - temporal
      - temporal-web
    networks:
      - temporal-network
    environment:
      - TEMPORAL_URL=temporal:7233

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
